# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: my first step
        env:
          my_var: Hi there, my name is 
          FIRST_NAME: yossi
          Last_name: didon
        run: echo $my_var $FIRST_NAME $Last_name
      - name: second step
        if: success()
        run: echo "The previous steps has finished successfully"
      - name: My third step
        uses: actions/checkout@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/ 
      - name: my forth step
        uses: actions/first-interaction@v1
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
         issue-message: 'Message that will be displayed on users'' first issue'
         pr-message: 'Message that will be displayed on users'' first pr'
          
